ALTER TABLE "listings"
  ADD COLUMN IF NOT EXISTS "is_hot" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "listing_houses"
  ADD COLUMN IF NOT EXISTS "material" VARCHAR(64),
  ADD COLUMN IF NOT EXISTS "area_living" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "area_kitchen" DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS "district_name" VARCHAR(128),
  ADD COLUMN IF NOT EXISTS "settlement" VARCHAR(128),
  ADD COLUMN IF NOT EXISTS "street" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "house_number" VARCHAR(64),
  ADD COLUMN IF NOT EXISTS "synonyms" VARCHAR(512),
  ADD COLUMN IF NOT EXISTS "distance_to_city" INTEGER,
  ADD COLUMN IF NOT EXISTS "direction_south" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "direction_north" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "direction_east" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "direction_west" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "in_belgorod_district" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "in_belgorod_region" BOOLEAN NOT NULL DEFAULT true;
