export enum RequestStatus {
  NEW = 'NEW',
  IN_PROGRESS = 'IN_PROGRESS',
  CONTACTED = 'CONTACTED',
  VIEWING_SCHEDULED = 'VIEWING_SCHEDULED',
  NEGOTIATION = 'NEGOTIATION',
  SUCCESS = 'SUCCESS',
  CLOSED = 'CLOSED',
  SPAM = 'SPAM',
  /** @deprecated use SUCCESS */
  COMPLETED = 'COMPLETED',
  /** @deprecated use CLOSED */
  CANCELLED = 'CANCELLED',
}

export enum RequestType {
  CONSULTATION = 'CONSULTATION',
  MORTGAGE = 'MORTGAGE',
  CALLBACK = 'CALLBACK',
  SELECTION = 'SELECTION',
  CONTACT = 'CONTACT',
}

export enum RequestEventType {
  CREATED = 'CREATED',
  ASSIGNED = 'ASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  NOTE_ADDED = 'NOTE_ADDED',
  CONTACTED = 'CONTACTED',
  VIEWING_SCHEDULED = 'VIEWING_SCHEDULED',
}
